//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBS_Shared.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please input a number.")]
        public string MSG_INPUT_NUMBER {
            get {
                return ((string)(this["MSG_INPUT_NUMBER"]));
            }
            set {
                this["MSG_INPUT_NUMBER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The valid number range is number > 0.")]
        public string MSG_INPUT_POSITIVE_NUMBER_WITHOUT_ZERO {
            get {
                return ((string)(this["MSG_INPUT_POSITIVE_NUMBER_WITHOUT_ZERO"]));
            }
            set {
                this["MSG_INPUT_POSITIVE_NUMBER_WITHOUT_ZERO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The valid number range is number ≥ 0.")]
        public string MSG_INPUT_POSITIVE_NUMBER_WITH_ZERO {
            get {
                return ((string)(this["MSG_INPUT_POSITIVE_NUMBER_WITH_ZERO"]));
            }
            set {
                this["MSG_INPUT_POSITIVE_NUMBER_WITH_ZERO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The valid temperature range is in between aaa ℃ ≤ Temperature ≤ bbb ℃.")]
        public string MSG_INPUT_NUMBER_RANGE_TEMPERATURE {
            get {
                return ((string)(this["MSG_INPUT_NUMBER_RANGE_TEMPERATURE"]));
            }
            set {
                this["MSG_INPUT_NUMBER_RANGE_TEMPERATURE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The valid pressure range is in between aaa mmAq ≤ Temperature ≤ bbb mmAq.")]
        public string MSG_INPUT_NUMBER_RANGE_PRESSURE {
            get {
                return ((string)(this["MSG_INPUT_NUMBER_RANGE_PRESSURE"]));
            }
            set {
                this["MSG_INPUT_NUMBER_RANGE_PRESSURE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You must select at least 1 gas type.")]
        public string MSG_CHECK_CHECKBOX {
            get {
                return ((string)(this["MSG_CHECK_CHECKBOX"]));
            }
            set {
                this["MSG_CHECK_CHECKBOX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The valid pressure range is in between aaa N㎥/hr ≤ Flow Rate ≤ bbb N㎥/hr.")]
        public string MSG_INPUT_NUMBER_RANGE_FLOWRATE {
            get {
                return ((string)(this["MSG_INPUT_NUMBER_RANGE_FLOWRATE"]));
            }
            set {
                this["MSG_INPUT_NUMBER_RANGE_FLOWRATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The valid cycle range is in between aaa ≤ Cycle(s) ≤ bbb.")]
        public string MSG_INPUT_NUMBER_RANGE_CYCLE {
            get {
                return ((string)(this["MSG_INPUT_NUMBER_RANGE_CYCLE"]));
            }
            set {
                this["MSG_INPUT_NUMBER_RANGE_CYCLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The valid range is in between aaa ≤ value(s) ≤ bbb.")]
        public string MSG_INPUT_VALUE_RANGE {
            get {
                return ((string)(this["MSG_INPUT_VALUE_RANGE"]));
            }
            set {
                this["MSG_INPUT_VALUE_RANGE"] = value;
            }
        }
    }
}
